#my_list=[1,2,-13,41,1,1]
#my_list.append(9999)
#my_list.insert(8000,999)
#print(*my_list)
#print(len(my_list))
#my_list.pop(2)
#print(*my_list)
#my_list_2=[5,6,7,8]
#new_lst=my_list+my_list_2
#print(*new_lst)
#cnt=my_list.count(2)
#print(cnt)
#my_list.sort()
#print(*my_list)
#agg functions
#cnt=my_list.count(1)
#print(cnt)
#my_list=list(map(int,input().split(",")))
#print(*my_list)
#list=["akshita","akshi","aki"]
#list.append("shylu")
#list.pop(2)
#print(*list)
list=list(map(int,input().split(" ")))
print("1.append")
print("2.pop")
print("3.sort")
print("4.hello,len")
choice=int(input())
if(choice==1):
   list.append(2)
elif(choice==2):
   list.pop(1)
elif(choice==3):
    list.sort()
else:
   a=len(list)
   print(f"hello len is{a}")
print(*list)       